version: '3'
services:
  dialog:
    image: acrlabx.azurecr.io/labxdialog:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.dialog.rule=Host(`labx.travelgatex.com`)"
      - "traefik.http.routers.dialogservice=dialog"
      - "traefik.http.services.dialog.loadbalancer.server.port=8080"
      - "traefik.http.routers.dialog.entrypoints=http"
    networks:
      - internet
networks:
  internet:
    external: true