apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-hotelx-flow
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-hotelx-flow
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-hotelx-flow
        image: acrlabx.azurecr.io/labxwebhook:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: azure-hotelx-flow
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-hotelx-flow