apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-hotelx-flow-deployment
spec:
  selector:
    matchLabels:
      app: azure-hotelx-flow
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: azure-hotelx-flow
    spec:
      containers:
      - name: azure-hotelx-flow
        image: acrlabx.azurecr.io/labxwebhook:latest
        ports:
        - containerPort: 80