package transaction

import ()
import "github.com/Arkiant/labxIII/src/webhook/transaction/http"
import "github.com/Arkiant/labxIII/src/webhook/pkg"

type SearchCriteria struct {
	CheckIn     pkg.Date `json:"checkIn"`
	ChecOut     pkg.Date `json:"checkOut"`
	Destination string   `json:"destination"`
	NumPaxes    int      `json:"numPaxes"`
}

type DestinationSearcherCriteria struct {
	Text    string `json:"text"`
	Access  string `json:"access"`
	MaxSize int    `json:"maxSize"`
}

type AutoGenerated struct {
	Data Data `json:"data"`
}
type DestinationSearcher struct {
	Code      string `json:"code"`
	Available bool   `json:"available"`
}
type HotelX struct {
	DestinationSearcher []DestinationSearcher `json:"destinationSearcher"`
}
type Data struct {
	HotelX HotelX `json:"hotelX"`
}

type SearchResponse struct {
	OptionID   string  `json:"optionID"`
	HotelName  string  `json:"hotelName"`
	Amount     float32 `json:"amount"`
	Currency   string  `json:"currency"`
	Refundable bool    `json:"refundable"`
}

type Service interface {
	Search(SearchCriteria) (SearchResponse, error)
	DestinationSearcher(DestinationSearcherCriteria) (string, error)
}

var _ Service = (*ServiceClient)(nil)

type ServiceClient struct {
	client http.Service
}

func NewService(c http.Service) Service {
	return &ServiceClient{
		client: c,
	}
}
