name: CI

on: [push, pull_request]

env:
  REGISTRY_NAME: acrlabx
  REGISTRY_BUILD_NAME: labxwebhook
  WORKING_DIRECTORY: ./src/webhook/

jobs:
  test:
    strategy:
      matrix: 
        go-version: [1.12, 1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install/Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./... -v
    - name: Build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: CGO_ENABLED=0 GOOS=linux go build -a -o service .

    # Docker build and publish
    - name: Docker set registry configuration 
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Docker build and publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REGISTRY_BUILD_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REGISTRY_BUILD_NAME }}:${{ github.sha }}
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REGISTRY_BUILD_NAME }}:latest
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REGISTRY_BUILD_NAME }}:latest