name: CI

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix: 
        go-version: [1.12, 1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install/Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Chackout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./... -v
    - name: Build
      run: ls -la && CGO_ENABLED=0 GOOS=linux go build -a -o service .
