name: CI

on: [push, pull_request]

env:
  REGISTRY_NAME: labxhx

jobs:
  test:

    strategy:
      matrix: 
        go-version: [1.12, 1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install/Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Chackout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./... -v
    - name: Build
      working-directory: ./src/webhook/
      run: CGO_ENABLED=0 GOOS=linux go build -a -o service .

    # Docker build and publish
    - name: Docker build and publish
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/labxwebhook:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/labxwebhook:${{ github.sha }}